### ISSUE TITLE
xFutures Tasks für die Woche

### ISSUE THREAD

**Issue by creyD** [creyD/project_zero#24]
- Designer anwerben (für Partikel, Texturen, Animationen)
- Buttontemplate erstellen

**Comment by xFuture603** [comment]
Status: - Niklas hat nach dem Abitur Zeit für solche Sachen. Weiß aber noch nicht wie er uns helfen kann, wenn er will.
- Template steht soweit,, mir ist nur unklar wieso die Buttons nicht funktionieren bzw. was ich vergessen habe.
